[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0.99" }
clap = { version = "4.5.47" }
crossterm = { version = "0.29.0" }
futures = { version = "0.3.31" }
ratatui = { version = "0.29.0" }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
tokio = { version = "1.47.1" }
tokio-util = { version = "0.7.16" }
