[package]
name = "cli"
version.workspace = true
edition.workspace = true

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"]}
crossterm = { workspace = true, features = ["event-stream"] }
dirs = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
ratatui = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread", "time", "signal", "sync"] }
tokio-util = { workspace = true, features = ["rt"] }
toml ={ workspace = true, features = ["serde"] }